### ISSUE TITLE
Will there be replay of the tutorial ?

### ISSUE THREAD

**Issue by TimHo0331** [araffin/tools-for-robotic-rl-icra2022#2]
Will there be replay of the tutorial ? 
For example, replay in Youtube...

**Comment by araffin** [comment]
Hello,
yes, we plan to livestream the tutorial or at least record it to put it online afterward ;)

**Comment by araffin** [comment]
Replay is here https://www.youtube.com/playlist?list=PL42jkf1t1F7etDiYXWC5Q77yIuVYhXNoy
